stages:
  - test
  - report

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

test:
  stage: test
  image: gradle:8.4-jdk17
  script:
    - gradle clean test
  artifacts:
    when: always
    paths:
      - build/allure-results
      - build/reports/tests/test
    expire_in: 1 week

allure-report:
  stage: report
  image: openjdk:17-jdk-slim
  script:
    - apt-get update && apt-get install -y wget unzip
    - wget -q https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.zip
    - unzip -q allure-2.24.0.zip -d /opt
    - /opt/allure-2.24.0/bin/allure generate build/allure-results -o build/allure-report --clean
  artifacts:
    when: always
    paths:
      - build/allure-report
    expire_in: 1 week
  needs: ["test"]
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      when: on_success

